{% set version = "0.1.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mlr3cluster
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mlr3cluster_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mlr3cluster/mlr3cluster_{{ version }}.tar.gz
  sha256: a413147211d2f3427ca5dc8894dde8af6c73f7c35c9e81deb47839e9fed2d116

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-backports >=1.1.10
    - r-checkmate
    - r-clue
    - r-cluster
    - r-data.table
    - r-fpc
    - r-mlr3 >=0.14.0
    - r-mlr3misc >=0.9.4
    - r-paradox
    - r-r6
  run:
    - r-base
    - r-backports >=1.1.10
    - r-checkmate
    - r-clue
    - r-cluster
    - r-data.table
    - r-fpc
    - r-mlr3 >=0.14.0
    - r-mlr3misc >=0.9.4
    - r-paradox
    - r-r6

test:
  commands:
    - $R -e "library('mlr3cluster')"           # [not win]
    - "\"%R%\" -e \"library('mlr3cluster')\""  # [win]

about:
  home: https://mlr3cluster.mlr-org.com
  dev_url: https://github.com/mlr-org/mlr3cluster
  license: LGPL-3.0-only
  summary: Extends the 'mlr3' package with cluster analysis.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - pascal-git
